
export const ImageData =[
    {
        id:1,
        imageSrc:'assets/img-1.jpg',
        tag:'Events'
    }, 
    {
        id:2,
        imageSrc:'assets/img-2.jpg',
        tag:'Ushering'
    },
    {
        id:3,
        imageSrc:'assets/img-3.jpg',
        tag:'Hosting'
    },
    {
        id:4,
        imageSrc:'assets/img-4.jpg',
        tag:'Events'
    },    {
        id:5,
        imageSrc:'assets/img-5.jpg',
        tag:'Ushering'
    },
    {
        id:6,
        imageSrc:'assets/img-6.jpg',
        tag:'Events'
    },
    {
        id:7,
        imageSrc:'assets/img1.jpg',
        tag:'Ushering'
    },
    {
        id:8,
        imageSrc:'assets/img2.jpg',
        tag:'Ushering'
    },
    {
        id:8,
        imageSrc:'assets/img3.jpg',
        tag:'Hosting'
    },
    {
        id:9,
        imageSrc:'assets/img4.jpg',
        tag:'Hosting'
    },
    {
        id:10,
        imageSrc:'assets/img5.jpg',
        tag:'Events'
    },
    {
        id:11,
        imageSrc:'assets/img-6.jpg',
        tag:'Ushering'
    },
    {
        id:12,
        imageSrc:'assets/img10.jpg',
        tag:'Events'
    },
    {
        id:13,
        imageSrc:'assets/img11.jpg',
        tag:'Hosting'
    },
    {
        id:14,
        imageSrc:'assets/img12.jpg',
        tag:'Ushering'
    },
    {
        id:15,
        imageSrc:'assets/img15.jpg',
        tag:'Hosting'
    }
]